name: release
env:
  GOWORK: off
on:
  push:
    tags:
      - "azkustodata/**"
      - "azkustoingest/**"

permissions:
  checks: write
  pull-requests: write
  packages: write
  deployments: write
  contents: write

jobs:
  build-data:
    if: startsWith(github.ref, 'refs/tags/azkustodata/')
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Release
        uses: docker://antonyurchenko/git-release:v6
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          TAG_PREFIX_REGEX: "azkustodata/v"

      - name: Pull new module version
        uses: andrewslotin/go-proxy-pull-action@master

  build-ingest:
    if: startsWith(github.ref, 'refs/tags/azkustoingest/')
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Release
        uses: docker://antonyurchenko/git-release:v6
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          TAG_PREFIX_REGEX: "azkustoingest/v"

      - name: Pull new module version
        uses: andrewslotin/go-proxy-pull-action@master
