name: release
env:
  GOWORK: off
on:
  push:
    tags:
      - "v[0-9]+.[0-9]+.[0-9]+(\-.*)?"

permissions:
  checks: write
  pull-requests: write
  packages: write
  deployments: write
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Release
        uses: docker://antonyurchenko/git-release:latest
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Pull new module version
        uses: andrewslotin/go-proxy-pull-action@master
